mysite/api/urls.py
from django.urls import path
from api import views


app_name = 'api'
urlpatterns = [
    path('v1/books', views.book_list, name='book_list')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url, include
from django.contrib.auth.models import User
#from rest_framework import routers, serializers, viewsets


# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ('url', 'username', 'email', 'is_staff')
#
#
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer
#
#
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)


urlpatterns = [
    path('sail/', include('sail.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    #url(r'^', include(router.urls)),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

mysite/sail/urls.py
from django.urls import path

from sail import views

app_name = 'sail'
urlpatterns = [
    # ポートフォリオページ
    path('', views.index, name='index'),  # トップ
    path('profile/', views.profile, name='profile'),  # プロフィール
    path('languages/', views.languages, name='languages'),  # 言語
    path('tools/', views.tools, name='tools'),  # ツール
    path('works/', views.works, name='works'),  # 仕事
    path('contacts/', views.contacts, name='contacts'),  # コンタクト
    # 書籍
    path('book/', views.book_list, name='book_list'),   # 一覧
    path('book/add/', views.book_edit, name='book_add'),  # 登録
    path('book/mod/<int:book_id>/', views.book_edit, name='book_mod'),  # 修正
    path('book/del/<int:book_id>/', views.book_del, name='book_del'),   # 削除
    # 感想
    path('impression/<int:book_id>/', views.ImpressionList.as_view(), name='impression_list'),  # 一覧
    path('impression/add/<int:book_id>/', views.impression_edit, name='impression_add'),  # 登録
    path('impression/mod/<int:book_id>/<int:impression_id>/', views.impression_edit, name='impression_mod'),  # 修正
    path('impression/del/<int:book_id>/<int:impression_id>/', views.impression_del, name='impression_del'),  # 修正
]

mysite/api/models.py
from django.db import models

# Create your models here.

mysite/sail/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    name = models.CharField('書籍名', max_length=255)
    publisher = models.CharField('出版社', max_length=255, blank=True)
    page = models.IntegerField('ページ数', blank=True, default=0)

    def __str__(self):
        return self.name


class Impression(models.Model):
    book = models.ForeignKey(Book, verbose_name='書籍', related_name='impressions', on_delete=models.CASCADE)
    comment = models.TextField('コメント', blank=True)
    impressions = models.TextField('コメント', blank=True)

    def __str__(self):
        return self.comment

mysite/sail/forms.py
from django.forms import ModelForm
from sail.models import Book, Impression


class BookForm(ModelForm):
    """書籍のフォーム"""
    class Meta:
        model = Book
        fields = ('name', 'publisher', 'page', )


class ImpressionForm(ModelForm):
    """感想のフォーム"""
    class Meta:
        model = Impression
        fields = ('comment',)

mysite/api/views.py
import json
from collections import OrderedDict
from django.http import HttpResponse
from sail.models import Book


def render_json_response(request, data, status=None):
    """responseをJSONで返却"""
    json_str = json.dumps(data, ensure_ascii=False, indent=2)
    callback = request.GET.get('callback')
    if not callback:
        callback = request.POST.get('callback')  # POSTでJSONPの倍医
    if callback:
        json_str = "%s(%s)" % (callback, json_str)
        response = HttpResponse(json_str, content_type='application/javascript; charset=UTF-8', status=status)
    else:
        response = HttpResponse(json_str, content_type='application/json; charset=UTF-8', status=status)
    return response


def book_list(request):
    """書籍と感想のJSONを返す"""
    books = []
    for book in Book.objects.all().order_by('id'):

        impressions = []
        for impression in book.imporessions.order_by('id'):
            impression_dict = OrderedDict([
                ('id', impression.id),
                ('comment', impression.comment),
            ])
            impressions.append(impression_dict)

        book_dict = OrderedDict([
            ('id', book.id),
            ('name', book.name),
            ('publisher', book.publisher),
            ('page', book.page),
            ('impressions', impressions)
        ])
        books.append(book_dict)

    data = OrderedDict([ ('books', books) ])
    return render_json_response(request, data)

mysite/sail/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.list import ListView
from django.http import HttpResponse
from sail.models import Book, Impression
from sail.forms import BookForm, ImpressionForm


def index(request):
    """トップページ"""
    return render(request,
                  'sail/index.html')


def profile(request):
    """プロフィールページ"""
    return render(request,
                  'sail/profile.html')


def languages(request):
    """言語ページ"""
    return render(request,
                  'sail/languages.html')


def tools(request):
    """ツールページ"""
    return render(request,
                  'sail/tools.html')


def works(request):
    """仕事ページ"""
    return render(request,
                  'sail/works.html')


def contacts(request):
    """コンタクトページ"""
    return render(request,
                  'sail/contacts.html')


def book_list(request):
    """書籍の一覧"""
    # return HttpResponse('書籍の一覧')
    books = Book.objects.all().order_by('id')
    return render(request,
                  'sail/book_list.html',    # 使用するテンプレート
                  {'books': books})         # テンプレートに渡すデータ


def book_edit(request, book_id=None):
    """書籍の編集"""
    # return HttpResponse('書籍の編集')
    if book_id:
        book = get_object_or_404(Book, pk=book_id)
    else:
        book = Book()

    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)  # POSTされたrequestからFormを作成する
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            return redirect('sail:book_list')
    else:
        form = BookForm(instance=book)  # book インスタンスからFormを作成

    return render(request, 'sail/book_edit.html', dict(form=form, book_id=book_id))


def book_del(request, book_id):
    """書籍の削除"""
    # return HttpResponse('書籍の削除')
    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    return redirect('sail:book_list')


class ImpressionList(ListView):
    """感想の一覧"""
    context_object_name='impressions'
    templete_namme='sail/impression_list.html'
    paginate_by = 2

    def get(self, request, *args, **kwarags):
        book = get_object_or_404(Book, pk=kwarags['book_id'])  # 親の書籍を読む
        impressions = book.impressions.all().order_by('id')  # 書籍の子供の感想を読む
        self.object_list = impressions

        context = self.get_context_data(object_list=self.object_list, book=book)
        return self.render_to_response(context)


def impression_edit(request, book_id, impression_id=None):
    """感想の編集"""
    book = get_object_or_404(Book, pk=book_id) # 親の書籍を読む
    if impression_id: # impression_idが指定されている（修正時）
        impression = get_object_or_404(Impression, pk=impression_id)
    else:
        impression = Impression()

    if request.method == 'POST':
        form = ImpressionForm(request.POST, instance=impression) # POSTされたrequestデータからフォームを作成
        if form.is_valid():
            impression = form.save(commit=False)
            impression.book = book # この感想の親の書籍をセット
            impression.save()
            return redirect('sail:impression_list', book_id=book_id)
    else:
        form = ImpressionForm(instance=impression) # impressionインスタンスからフォームを作成

    return render(request,
                  'sail/impression_edit.html',
                  dict(form=form, book_id=book_id, impression_id=impression_id))


def impression_del(request, book_id, impression_id):
    """感想の削除"""
    impression = get_object_or_404(Impression, pk=impression_id)
    impression.delete()
    return redirect('sail:impression_list', book_id=book_id)

mysite/sail/templates/sail/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'sail/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'sail/css/style.css' %}">
{% block extra_css %}{% endblock %}
<title>{% block title %}YUSUKE.Y PORTFOLIO{% endblock %}</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>
  <header class="header-outer">
    <div class="header-inner">
      <div class="header-content">
        <div class="header-left">
          <div class="header-title"><a href="{% url 'sail:index' %}" style="text-decoration: none; color: white">YUSUKE.Y PORTFOLIO</a></div>
        </div>
        <div class="header-menu">
          <nav class="header-navi">
            <ul class="header-navi-list">
              <li class="header-navi-item" data-id="index"><a class="top-link" href="{% url 'sail:index' %}">TOP</a></li>
              <li class="header-navi-item" data-id="menu2"><a class="top-link" href="{% url 'sail:profile' %}">PROFILE</a></li>
              <li class="header-navi-item" data-id="menu3"><a class="top-link" href="{% url 'sail:languages' %}">LANGUAGES</a></li>
              <li class="header-navi-item" data-id="menu4"><a class="top-link" href="{% url 'sail:tools' %}">TOOLS</a></li>
              <li class="header-navi-item" data-id="menu5"><a class="top-link" href="{% url 'sail:works' %}">WORKS</a></li>
              <li class="header-navi-item" data-id="menu5"><a class="top-link" href="{% url 'sail:contacts' %}">CONTACTS</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>
  <div class="body-base">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
<script src="{% static 'sail/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'sail/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'sail/js/style.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

mysite/sail/templates/sail/book_edit.html
{% extends "sail/base.html" %}
{% load bootstrap4 %}

{% block title %}書籍の編集{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">書籍の編集</h4>
    {% if book_id %}
    <form action="{% url 'sail:book_mod' book_id=book_id %}" method="post">
    {% else %}
    <form action="{% url 'sail:book_add' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'sail:book_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

mysite/sail/templates/sail/book_list.html
{% extends "sail/base.html" %}

{% block title %}書籍の一覧{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">書籍の一覧</h4>
    <a href="{% url 'sail:book_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">書籍名</th>
          <th scope="col">出版社</th>
          <th scope="col">ページ数</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for book in books %}
        <tr>
          <th scope="row">{{ book.id }}</th>
          <td>{{ book.name }}</td>
          <td>{{ book.publisher }}</td>
          <td>{{ book.page }}</td>
          <td>
            <a href="{% url 'sail:book_mod' book_id=book.id %}" class="btn btn-outline-primary btn-sm">修正</a>
            <a href="{% url 'sail:book_del' book_id=book.id %}" class="btn btn-outline-danger btn-sm">削除</a>
            <a href="{% url 'sail:impression_list' book_id=book.id %}" class="btn btn-outline-info btn-sm">感想の一覧</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock content %}

mysite/sail/templates/sail/contacts.html
{% extends "sail/base.html" %}

{% block content %}
{% load static %}
    <h2 class="title">CONTACTS</h2>
    <div class="center-pos">
        <h4>GitHub</h4>
        <a href="https://github.com/yusukeyama"><img class="center-img" src="{% static 'sail/img/github_icon.png' %}" alt="icon" ></a>
    </div>
    <div class="center-pos">
        <h4>Qiita</h4>
        <a  href="https://qiita.com/yusukeyama"><img class="center-img" src="{% static 'sail/img/qiita-favicon.png' %}" alt="icon" ></a>
    </div>
{% endblock content %}

mysite/sail/templates/sail/impression_edit.html
{% extends "sail/base.html" %}
{% load bootstrap4 %}

{% block title %}感想の編集{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">感想の編集</h4>
    {% if impression_id %}
    <form action="{% url 'sail:impression_mod' book_id=book_id impression_id=impression_id %}" method="post">
    {% else %}
    <form action="{% url 'sail:impression_add' book_id=book_id %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'sail:impression_list' book_id=book_id %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

mysite/sail/templates/sail/impression_list.html
{% extends "sail/base.html" %}

{% block title %}感想の一覧{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom">感想の一覧 <small class="text-muted ml-3">{{ book.name }}</small></h4>
    <a href="{% url 'sail:impression_add' book_id=book.id %}" class="btn btn-primary btn-sm my-3">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>コメント</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for impression in impressions %}
        <tr>
          <td>{{ impression.id }}</td>
          <td>{{ impression.comment|linebreaksbr }}</td>
          <td>
            <a href="{% url 'sail:impression_mod' book_id=book.id impression_id=impression.id %}" class="btn btn-outline-primary btn-sm">修正</a>
            <button class="btn btn-outline-danger btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" data-pk="{{ impression.id }}" data-url="{% url 'sail:impression_del' book_id=book.id impression_id=impression.id %}">削除</button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
    <nav aria-label="Page navigation">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
        {% endif %}
        {% for linkpage in page_obj.paginator.page_range %}
          {% ifequal linkpage page_obj.number %}
            <li class="page-item active"><a class="page-link" href="#">{{ linkpage }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

    <a href="{% url 'sail:book_list' %}" class="btn btn-secondary btn-sm">戻る</a>

    {# 削除を確認するモーダル ダイアログ #}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">確認</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
            <p>ID: <span id="del_pk"></span> を削除しますか？</p>
          </div>
          <div class="modal-footer">
            <a href="#" class="btn btn-primary" id="del_url">OK</a>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block extra_js %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).data("pk"));
     $('#del_url').attr('href', $(this).data("url"));
  });
});
</script>
{% endblock %}

mysite/sail/templates/sail/index.html
{% extends "sail/base.html" %}

{% block content %}
    <div class="gradient-area top-area">
        <div class="wave -one"></div>
        <div class="wave -two"></div>
        <div class="wave -three"></div>
        <h1>YUSUKE.YAMANISHI PORTFOLIO PAGE</h1>
    </div>
{% endblock content %}

mysite/sail/templates/sail/languages.html
{% extends "sail/base.html" %}

{% block content %}
    <h2 class="title">LANGUAGES</h2>
    <div class="container">
        <div class="row">
            <div class="col-xl-4 box-container">
                <h2 class="box-header">C#</h2>
                <p class="box-body">主にUnityで使用していました。トップクラスに使い込んだ言語ですが、あくまでもUnityに特化しており、windows向けはしたことないという…</p>
                <p>使用歴：2年</p>
            </div>
            <div class="col-xl-4 box-container">
                <h2 class="box-header">Java</h2>
                <p class="box-body">Androidで使用していました。エンジニアなりたての頃で非常に覚えるのに苦労した覚えが。今となってはいい思い出です。</p>
                <p>使用歴：2年</p>
            </div>
            <div class="col-xl-4 box-container">
                <h2 class="box-header">PHP</h2>
                <p class="box-body">API作ったり、今はWebサービス開発でがっつり使ってます。フレームワークはCakePHP使用。</p>
                <p>使用歴：2年</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-4 box-container">
                <h2 class="box-header">Kotlin</h2>
                <p class="box-body">kotlinがandroidに採用されて使ってみることに。そしたら書きやすくて現在僕の中でトップクラスに評価が高い言語になる。型推論の軽やかさと安全性を両立していて好感触。</p>
                <p>使用歴：6ヶ月</p>
            </div>
            <div class="col-xl-4 box-container">
                <h2 class="box-header">Python</h2>
                <p class="box-body">Djangoでweb開発やりたくて使用。ディープラーニングやるときも使えると思い選択。PHPより書きやすくて感動した。</p>
                <p>使用歴：数ヶ月</p>
            </div>
            <div class="col-xl-4 box-container">
                <h2 class="box-header">swift</h2>
                <p class="box-body">xcodeでiOSネイティブアプリ作った事ないなーと思い使ってみた。kolinに似てて良い感じかと。</p>
                <p>使用歴：6ヶ月</p>
            </div>
        </div>
    </div>
{% endblock content %}

mysite/sail/templates/sail/profile.html
{% extends "sail/base.html" %}

{% block content %}
    <h2 class="title">PROFILE</h2>
    <div class="profile-area">
        <table class="profile-area-cont">
            <tbody>
                <tr class="small-title-border">
                    <th class="small-title">
                        NAME
                    </th>
                    <td>
                        山西 悠祐（Yusuke Yamanishi）
                    </td>
                </tr>
                <tr class="small-title-border">
                    <th class="small-title">
                        OCCUPATION
                    </th>
                    <td>
                        Webエンジニア
                    </td>
                </tr>
                <tr class="small-title-border">
                    <th class="small-title">
                        PROFESSTIONAL AREA
                    </th>
                    <td>
                        Web・モバイルアプリ
                    </td>
                </tr>
                <tr class="small-title-border">
                    <th class="small-title">
                        JOB EXPERIENCE
                    </th>
                    <td>
                        スマートフォン向けゲーム開発
                    </td>
                </tr>
                <tr class="small-title-border">
                    <th class="small-title">

                    </th>
                    <td>
                        Webサービス開発
                    </td>
                </tr>
                <tr class="small-title-border">
                    <th class="small-title">
                        INTEREST
                    </th>
                    <td>
                        Webフロント、サーバーサイド
                    </td>
                </tr>
                <tr class="small-title-border">
                    <th class="small-title">

                    </th>
                    <td>
                        モバイルアプリ、機械学習、IoT
                    </td>
                </tr>
                <tr class="small-title-border">
                    <th class="small-title">
                        INTRODUCTION
                    </th>
                    <td>
                        20代半ばからエンジニアの道に。
                    </td>
                </tr>
                <tr class="small-title-border">
                    <th class="small-title">

                    </th>
                    <td>
                        現在はIoT企業で仕事中。
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock content %}

mysite/sail/templates/sail/tools.html
{% extends "sail/base.html" %}

{% block content %}
    <h2 class="title">TOOLS</h2>
    <div class="container">
        <div class="row">
            <div class="col-xl-4 box-container">
                <h2 class="box-header">Git</h2>
                <p class="box-body">エンジニアになりたての頃から使用。最初は何度もコンフリクト起こりまくったけど今は完璧に使えるように。rebase愛好者。</p>
            </div>
            <div class="col-xl-4 box-container">
                <h2 class="box-header">PhpStorm</h2>
                <p class="box-body">PHPの開発で使い始めたら使いやすくて虜に。とにかく静的解析が優秀すぎてどんどんコード書ける。AndroidStudioとUIが似ていて親しみやすいのもグッド。</p>
            </div>
            <div class="col-xl-4 box-container">
                <h2 class="box-header">VisualStudioCode</h2>
                <p class="box-body">愛用のエディタ。PhpStorm使うようになってからは出番は減ったけど相変わらず軽くて使いやすい。1年くらい愛用している。拡張機能追加でどんな状況にも対応できる。</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-4 box-container">
                <h2 class="box-header">Mac</h2>
                <p class="box-body">会社がMac使ってて使うことに。環境構築とかunix系であることとかが便利すぎてプライベートでもMac使いに。</p>
            </div>
        </div>
    </div>
{% endblock content %}

mysite/sail/templates/sail/works.html
{% extends "sail/base.html" %}

{% block content %}
    <h2 class="title">WORKS</h2>
    <div class="container">
        <div class="row">
            <div class="col-xl-6 box-container">
                <h2 class="box-header">ポートフォリオページ</h2>
                <p class="box-body">このWebサイト。自分のスキルとか棚卸しするためと今まで学んだWeb技術で作りたくて作成。随時情報は追加予定。＊Workにはプライベートで関わったもののみ掲載していきます。</p>
            </div>
            <div class="col-xl-6 box-container">
                <h2 class="box-header">シンプルメモ</h2>
                <p class="box-body">Android個人リリース第1弾。とにかく軽く何かをリリースしたくて作成。そこそこインストール数伸びてて意外な収穫があった。</p>
                <a href="https://play.google.com/store/apps/details?id=yusukey.com.crypto_memo"><p class="box-body">GooglePlay</p></a>
            </div>
        </div>
    </div>
{% endblock content %}